version: '3.8'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - STAGE=dev
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ptm
      - DB_USER=ptm
      - DB_PASSWORD=ptm
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@localhost.com
    depends_on:
      - db
  db:
    image: mysql:8.3
    environment:
      - MYSQL_USER=ptm
      - MYSQL_PASSWORD=ptm
      - MYSQL_DATABASE=ptm
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ptm_db:/var/lib/mysql
      

volumes:
  ptm_db: