version: '3.8'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-ptm:/data/db

volumes:
  mongo-ptm:
