version: '3.8'
services:
  backend:
    image: 471112594514.dkr.ecr.us-east-1.amazonaws.com/pmt:development
    ports:
      - "80:80"
    environment:
      - RUN_PORT=80
    restart: always
    env_file:
      - .env
