version: '3'

# dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  aws:
    taskfile: "./.taskci/task-templates/templates/aws.yml"

tasks:
  backend:pull:
    desc: Pull the latest changes from the backend repository
    cmds:
      - git pull
  
  backend:build:
    desc: Build the backend image and push it to ECR
    deps:
      - backend:pull
    cmds:
      - task: aws:ecr-build-push
        vars:
          IMAGE_TAG: "development"
          AWS_DEFAULT_REGION: "us-east-1"
          ECR_REPOSITORY: "pmt"
          PATH: "./backend"

  backend:start:
    desc: Start the backend container
    deps:
    - backend:build
    cmds:
      - docker compose -f docker-compose.prod.yml up -d
  
  ui:push:
    desc: Push the UI changes to CloudFront
    cmds:
    - task: aws:npm-build
      vars:
        PATH: "./ui"
        BUILD_DIR: "out"
        CF_PUSH: "true"
        CF_DISTRIBUTION_ID: "ENGIBT49ANBXI"
        CF_S3_BUCKET: "pmt-ui"

  docker:clean:
    desc: Clean up dangling unwanted docker images and containers
    cmds:
      - docker system prune -f
