# Generated by Django 5.0.1 on 2024-01-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255, unique=True)),
                ("client_email", models.EmailField(max_length=254, unique=True)),
                ("client_project_manager", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_code", models.CharField(max_length=255, unique=True)),
                ("project_manager", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("client_project_manager", models.CharField(max_length=255)),
                ("incidence_rate", models.CharField(max_length=50)),
                ("loi", models.CharField(max_length=10)),
                ("scope", models.IntegerField()),
                ("target", models.CharField(max_length=100)),
                ("target_description", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=100)),
                ("online", models.CharField(max_length=100)),
                ("methodology", models.CharField(blank=True, max_length=100)),
                ("billing_comments", models.CharField(max_length=500)),
                ("security_check", models.BooleanField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=255)),
                ("vendor_code", models.CharField(max_length=255, unique=True)),
                ("scope", models.IntegerField()),
                ("complete", models.CharField(max_length=255)),
                ("terminate", models.CharField(max_length=255)),
                ("over_quota", models.CharField(max_length=255)),
                ("pause_vendor", models.BooleanField()),
                ("vendor_name", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectcreation",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=255)),
                ("input_field", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=10)),
                ("scope", models.IntegerField()),
                ("test_link", models.URLField()),
                ("live_link", models.URLField()),
                ("check_country", models.BooleanField()),
                ("check_quota", models.BooleanField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectcreation",
                    ),
                ),
            ],
            options={
                "unique_together": {("project_code", "country_code")},
            },
        ),
    ]
