# Generated by Django 5.0.1 on 2024-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcreation",
            name="loi",
            field=models.CharField(max_length=10),
        ),
    ]
