# Generated by Django 5.0.1 on 2024-01-17 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcreation",
            name="selected_div",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="ProjectVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=255)),
                ("vendor_code", models.CharField(max_length=255)),
                ("scope", models.IntegerField()),
                ("complete", models.CharField(max_length=255)),
                ("terminate", models.CharField(max_length=255)),
                ("over_quota", models.CharField(max_length=255)),
                ("pause_vendor", models.BooleanField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectcreation",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.vendor"
                    ),
                ),
            ],
        ),
    ]
