# Generated by Django 5.0.1 on 2024-01-19 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="client_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="client_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="client_project_manager",
            new_name="project_manager",
        ),
    ]
