# Generated by Django 5.0.1 on 2024-01-24 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_client_email_client_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectcreation",
            name="scope",
        ),
    ]
