# Generated by Django 5.0.1 on 2024-01-18 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_projectcreation_selected_div_projectvendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcreation",
            old_name="selected_div",
            new_name="methodology",
        ),
        migrations.RenameField(
            model_name="projectcreation",
            old_name="selected_project_status",
            new_name="status",
        ),
    ]
