# Generated by Django 5.0.1 on 2024-01-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_projectcreation_loi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="projectclient",
            name="scope",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="projectclient",
            unique_together={("project_code", "country_code")},
        ),
        migrations.AlterField(
            model_name="projectcreation",
            name="project_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.projectcode"
            ),
        ),
    ]
