# Generated by Django 5.0.1 on 2024-01-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_projectcreation_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSurveyTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=225, unique=True)),
                ("test", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        db_default=models.Value("insurvey"), max_length=225
                    ),
                ),
                ("vendor_code", models.CharField(max_length=225)),
                ("vendor_id", models.CharField(max_length=225)),
                ("country", models.CharField(max_length=225)),
                ("county_code", models.CharField(max_length=225)),
                ("ip_address", models.CharField(blank=True, max_length=225, null=True)),
                ("fraud_score", models.IntegerField(blank=True, null=True)),
                ("ip_proxy", models.BooleanField(default=False)),
                ("ip_region", models.CharField(blank=True, max_length=225, null=True)),
                ("qc_remarks", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectcreation",
                    ),
                ),
            ],
        ),
    ]
