# Generated by Django 5.0.1 on 2024-01-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_projectcreation_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclient",
            name="index_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projectvendor",
            name="vendor_code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="projectvendor",
            unique_together={("project_code", "vendor_code")},
        ),
        migrations.CreateModel(
            name="ProjectSurveyTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=225, unique=True)),
                ("test", models.BooleanField(db_default=models.Value(False))),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        db_default=models.Value("insurvey"), max_length=225
                    ),
                ),
                ("project_code", models.CharField(max_length=225)),
                ("vendor_code", models.CharField(max_length=225)),
                ("vendor_id", models.CharField(max_length=225)),
                ("country", models.CharField(max_length=225)),
                ("county_code", models.CharField(max_length=225)),
                ("ip_address", models.CharField(blank=True, max_length=225, null=True)),
                ("fraud_score", models.IntegerField(blank=True, null=True)),
                ("ip_proxy", models.BooleanField(db_default=models.Value(False))),
                ("ip_region", models.CharField(blank=True, max_length=225, null=True)),
                ("qc_remarks", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "project_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectclient",
                    ),
                ),
                (
                    "project_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.projectvendor",
                    ),
                ),
            ],
        ),
    ]
