# Generated by Django 5.0.1 on 2024-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_selected_div_projectcreation_methodology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectvendor",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projectvendor",
            name="vendor_code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
