# Generated by Django 5.0.1 on 2024-01-30 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_projectclient_index_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectsurveytrace",
            old_name="county_code",
            new_name="country_code",
        ),
    ]
