# Generated by Django 5.0.1 on 2024-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_projectvendor_vendor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectvendor",
            name="vendor_name",
            field=models.CharField(max_length=255),
        ),
    ]
