# Generated by Django 5.0.1 on 2024-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_projectsurveytrace"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclient",
            name="index_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projectvendor",
            name="vendor_code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="projectvendor",
            unique_together={("project_code", "vendor_code")},
        ),
    ]
