# Generated by Django 5.0.1 on 2024-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_projectclient_index_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsurveytrace",
            name="ip_proxy",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="projectsurveytrace",
            name="test",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
