# Generated by Django 5.0.1 on 2024-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_county_code_projectsurveytrace_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectvendor",
            name="index_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectclient",
            name="index_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
