# Generated by Django 5.0.1 on 2024-02-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_rename_check_country_projectclient_country_pause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsurveytrace",
            name="project_vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.projectvendor",
            ),
        ),
    ]
