# Generated by Django 5.0.1 on 2024-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_projectsurveytrace_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcreation",
            name="scope",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
