# Generated by Django 5.0.1 on 2024-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_projectcreation_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcreation",
            name="scope",
            field=models.IntegerField(),
        ),
    ]
