# Generated by Django 5.0.2 on 2024-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_appuser_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="last_token_refresh",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="role",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
