# Generated by Django 5.0.2 on 2024-02-12 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_appuser_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="appuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="user_permissions",
        ),
    ]
