# Generated by Django 5.0.2 on 2024-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_alter_appuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(db_default=True),
        ),
    ]
