# Generated by Django 5.0.2 on 2024-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_projectsurveytrace_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsurveytrace",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
